# Generated by Django 5.1.2 on 2024-10-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_model',
            options={'verbose_name': 'ticket'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterModelTable(
            name='ticket_model',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
